# Generated by Django 5.0 on 2023-12-30 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('model', models.CharField(max_length=200, verbose_name='модель')),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата релиза продукта')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('street', models.CharField(max_length=100, verbose_name='улица')),
                ('building', models.CharField(max_length=20, verbose_name='дом')),
                ('type', models.CharField(choices=[('завод', 'Factory'), ('розничная сеть', 'Retail Network'), ('индивидуальный предприниматель', 'Entrepreneur')], max_length=30, verbose_name='тип компании')),
                ('supplier_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='долг поставщику')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время создания')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='поставщик')),
                ('products', models.ManyToManyField(to='companies.product', verbose_name='товары')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ('name',),
            },
        ),
    ]
