# Generated by Django 5.0 on 2023-12-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('Завод', 'Завод'), ('Розничная сеть', 'Розничная сеть'), ('Индивидуальный предприниматель', 'Индивидуальный предприниматель')], max_length=30, verbose_name='тип компании'),
        ),
    ]
